login:
    path:     /login
    defaults: { _controller: juzzUsuariosBundle:Default:login}
# Ruta para la acción que comprueba el login del frontend
login_check:
    path:   /login_check
# Ruta para la acción de logout de los usuarios del frontend extranet
logout:
    path:   /logout

register:
    path:     /register
    defaults: { _controller: juzzUsuariosBundle:Registration:registro}
check_email:
    path:    /check-email
    defaults: { _controller: juzzUsuariosBundle:Registration:checkEmail}
confirm:
    path:  /confirm/{token}
    defaults: { _controller: juzzUsuariosBundle:Registration:confirm}
    requirements:
        user:  \w*
        methods: GET
confirmed:
    path: /confirmed
    defaults: { _controller: juzzUsuariosBundle:Registration:confirmed}
    requirements:
        user:  \w*
        methods: GET
perfil:
    path:     /{user}
    defaults: { _controller: juzzUsuariosBundle:Profile:show}
    requirements:
        user:  \w*
editar_perfil:
    path:     /{user}/edit
    defaults: { _controller: juzzUsuariosBundle:Profile:edit}
    requirements:
        user:  \w+
mis_comentarios:
    path:   /{user}/myComments
    defaults: {_controller: juzzUsuariosBundle:Profile:myComments}
    requirements:
        user:  \w+
#Followers
add_follower:
    path:   /{user}/followers/{follower}/add
    defaults: {_controller: juzzUsuariosBundle:Followers:add}
    requirements:
        user:  \w+
        follower: \w+
delete_follower:
    path:   /{user}/followers/{follower}/delete
    defaults: {_controller: juzzUsuariosBundle:Followers:delete}
    requirements:
        user:  \w+
        follower: \w+
followers:
    path:   /{user}/followers/
    defaults: {_controller: juzzUsuariosBundle:Followers:show}
    requirements:
        user:  \w+



