# Ruta Login.
login:
    path:     /accounts/login
    defaults: { _controller: juzzUsuariosBundle:Default:login}
# Ruta para la acción que comprueba el login del frontend
login_check:
    path:   /accounts/login_check
# Ruta para la acción de logout de los usuarios.
logout:
    path:   /accounts/logout
# Ruta Registro de Usuarios.
register:
    path:     /accounts/register
    defaults: { _controller: juzzUsuariosBundle:Registration:register}
# Indica al usuario que revise su correo para ver las instrucción de activación.
check_email:
    path:    /accounts/check-email
    defaults: { _controller: juzzUsuariosBundle:Registration:checkEmail}
# Ruta para activación de Cuentas.
confirm:
    path:  /accounts/confirm/{token}
    defaults: { _controller: juzzUsuariosBundle:Registration:confirm}
    methods:  [GET]
    requirements:
        token:  .{43}
# Ruta para indicar que la cuenta ha sido activada
confirmed:
    path: /accounts/confirmed/{user}
    defaults: { _controller: juzzUsuariosBundle:Registration:confirmed}
    methods:  [GET]
    requirements:
        user:  \w*
# Solicitud de reseteo de contraseña
resetting_request:
    path: /accounts/request
    defaults:
        _controller: FrameworkBundle:Template:template
        template: juzzUsuariosBundle:Accounts:resetting/request.html.twig
# Envío de email para completar reseteo de contraseña
resetting_send_email:
    path: /accounts/send-email
    defaults: { _controller: juzzUsuariosBundle:Resetting:sendEmail}
    methods:  [POST]
# Indica al usuario que compruebe su email para completar el reseteo de la password
resetting_check_email:
    path: /accounts/check-email
    defaults: { _controller: juzzUsuariosBundle:Resetting:checkEmail}
    methods:  [GET]
# Realiza el reseteo en caso de que el token sea correcto
resetting_reset:
    path: /accounts/reset/{token}
    defaults: { _controller: juzzUsuariosBundle:Resetting:reset}
    methods:  [GET|POST]
    requirements:
        token:  .{43}
# Ruta del perfil del usuario.
perfil:
    path:     /usuarios/{user}
    defaults: { _controller: juzzUsuariosBundle:Profile:show}
    requirements:
        user:  \w*
# Ruta para editar perfil del usuario.
editar_perfil:
    path:     /usuarios/{user}/edit
    defaults: { _controller: juzzUsuariosBundle:Profile:edit}
    requirements:
        user:  \w+
mis_comentarios:
    path:   /usuarios/{user}/myComments
    defaults: {_controller: juzzUsuariosBundle:Profile:myComments}
    requirements:
        user:  \w+
#Followers
add_follower:
    path:   /usuarios/{user}/followers/{follower}/add
    defaults: {_controller: juzzUsuariosBundle:Followers:add}
    requirements:
        user:  \w+
        follower: \w+
delete_follower:
    path:   /usuarios/{user}/followers/{follower}/delete
    defaults: {_controller: juzzUsuariosBundle:Followers:delete}
    requirements:
        user:  \w+
        follower: \w+
followers:
    path:   /usuarios/{user}/followers/
    defaults: {_controller: juzzUsuariosBundle:Followers:show}
    requirements:
        user:  \w+



