parameters:
    juzz.resetting.email.template: 'juzz:Resetting:email.txt.twig'
    juzz.registration.confirmation.template: 'juzz:Registration:email.txt.twig'
    
services:
    juzz.mailer:
       class: juzz\UsuariosBundle\Mailer\Mailer
       public: false
       arguments: [mailer,router,templating,{confirmation.template: %juzz.registration.confirmation.template%, resetting.template:%juzz.resetting.email.template%, form_email : {confirmation: '', resetting: ''} }]
    juzz.util.token_generator:
       class: juzz\UsuariosBundle\Util\TokenGenerator
       public: false
       arguments: [logger]
    juzz.listener.email_confirmation:
       class: juzz\UsuariosBundle\EventListener\EmailConfirmationListener
       arguments: ['@juzz.mailer','@juzz.util.token_generator',router,session]
       tags:
            -  { name: kernel.event_subscriber }