parameters:
  juzz.resetting.email.template: 'juzz:Resetting:email.txt.twig'
  juzz.registration.confirmation.template: 'juzzUsuariosBundle:Mail:email.txt.twig'
services:
  security.authentication.success_handler:
    class:  juzz\UsuariosBundle\Service\LoginSuccessHandler
    arguments: [@router, @security.context]
  juzz.mailer:
    class: juzz\UsuariosBundle\Mailer\Mailer
    public: false
    arguments: ["@hip_mandrill.dispatcher","@router","@templating","@logger",{confirmation.template: %juzz.registration.confirmation.template%, resetting.template:%juzz.resetting.email.template%}]
  juzz.util.token_generator:
    class: juzz\UsuariosBundle\Util\TokenGenerator
    public: false
    arguments: ["@logger"]
  juzz.listener.email_confirmation:
    class: juzz\UsuariosBundle\EventListener\EmailConfirmationListener
    arguments: ['@juzz.mailer','@juzz.util.token_generator',"@router","@session",%required_user_activation%,"@logger"]
    tags:
      -  { name: kernel.event_subscriber }