imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator: { fallback: es }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true , enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: :default:partials/hinclude.html.twig
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments: { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['juzzUsuariosBundle:Form:form-radio-button.html.twig','juzzUsuariosBundle:Form:terminos-tags-input.html.twig','juzzUsuariosBundle:Form:select-control.html.twig','juzzFilesBundle:Form:profile-image.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
          enum: string

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Configuración del Bundle de Usuarios.
juzz_usuarios:
    registration:
        required_user_activation: true
        auto_login_when_confirmed: true
    resetting:
        token_ttl: 86400

hip_mandrill:
    api_key: 6bbwzrWRJHAJAM-ewoX8vA
    disable_delivery: false # useful for dev/test environment. Default value is 'false'
    # debug: passed to \Mandrill causing it to output curl requests. Useful to see output
    # from CLI script. Default value is 'false'
    debug: false
    default:
        sender: equipo-juzz@gmail.com
        sender_name: Equipo Juzz # Optionally define a sender name (from name)
    proxy: ~

dcs_opauth:
    debug_mode: false              # (boolean) Whether debug messages are to be displayed
    callback_transport: session    # ('session','post','get') HTTP transport type, for sending of Auth response
    security_iteration: 300        # (int) The number of times hashing is done to sign auth response
    security_timeout: 2 minutes 
    redirect_after_response: http://localhost/juzz/web/app_dev.php/usuarios/accounts?tab=register&method=social
    strategies:
        facebook:
            id:             732244713585713
            secret:         'b1f2aaacba6ec0efd169d79051ecdff5'
            strategy_class: Facebook
            options:
                scope: ['public_profile','email']

lopi_pusher:
    app_id: 158835
    key: 'e3feeec9c2b05b1c6f12'
    secret: 'f08efc75370710229fdd'

    # Default configuration
    debug: true # true if you want use the debug of all requests
    host: http://api.pusherapp.com
    port: 80
    timeout: 30

# FOSJsRoutingBundle configuration see more https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md
fos_js_routing:
    routes_to_expose: [ 'comments' , 'post_comment' , 'push_notifications' , 'perfil' , 'comment_assess']

# Bundle Trabajo con bootstrap
braincrafted_bootstrap:
    icon_prefix: fa
    auto_configure:
        assetic: false
        twig: true
        knp_menu: true
        knp_paginator: true
# Bundle Subida de archivos
vich_uploader:
    db_driver: orm
    mappings:
        user_avatar:
            uri_prefix:         /img/avatares
            upload_destination: %kernel.root_dir%/../web/img/avatares
            delete_on_update:   true
            delete_on_remove:   true
        user_profile_bg:
            uri_prefix:         /img/profilesbg
            upload_destination: %kernel.root_dir%/../web/img/profilesbg
            delete_on_update:   true
            delete_on_remove:   true

services:
    twig.mobile_detect_extension:
        class: Bes\Twig\Extension\MobileDetectExtension
        tags:
            - { name: twig.extension }