
juzz_notifications:
    resource: "@juzzNotificationsBundle/Resources/config/routing.yml"
    prefix:   /

juzz_comments:
    resource: "@juzzCommentsBundle/Resources/config/routing.yml"
    prefix:   /


juzz_files:
    resource: "@juzzFilesBundle/Resources/config/routing.yml"
    prefix:   /


# Rutas importadas del bundle UsuariosBundle
juzz_usuarios:
    resource: "@juzzUsuariosBundle/Resources/config/routing.yml"
    prefix:   /

# Rutas importadas del bundle CanalesBundle
juzz_canales:
    resource: "@juzzCanalesBundle/Resources/config/routing.yml"
    prefix:   /canales
# Rutas importadas del bundle ProgramasBundle
juzz_programas:
    resource: "@juzzProgramasBundle/Resources/config/routing.yml"
    prefix:   /{channel}/programas
    requirements:
        channel: .+
# Primer listado de rutas importadas del bundle EpisodiosBundle
juzz_canales_episodios:
    resource: "@juzzEpisodiosBundle/Resources/config/routing_one.yml"
    prefix:   /{channel}/{program}/episodios
    requirements:
        channel: \w+
        program: \w+
# Segundo listado de rutas importadas del bundle EpisodiosBundle
juzz_episodios:
    resource: "@juzzEpisodiosBundle/Resources/config/routing_two.yml"
    prefix:   /episodios

portada:
  path:  /
  defaults: { _controller: juzzUsuariosBundle:Default:index }

dcs_opauth_connect:
    resource: "@DCSOpauthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

dcs_opauth_response:
    resource: "@DCSOpauthBundle/Resources/config/routing/response.xml"
    prefix: /connect

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
