security:

    firewalls:
        frontend:
            pattern:        ^/*
            provider:       users
            anonymous:      ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:    logout
                target:  /
            remember_me:
                key:        juzz_cookie
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/usuario/(login|registro), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USER }

    encoders:
        juzz\UsuariosBundle\Entity\Usuarios:        { algorithm: sha512, iterations: 10 }

    providers:
        # Usuarios del frontend
        users:
            entity: { class: juzz\UsuariosBundle\Entity\Usuarios, property: email }

