security:

    firewalls:
        frontend:
            pattern:        ^/*
            provider:       users
            anonymous:      ~
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: email
                password_parameter: password
                success_handler: security.authentication.success_handler
            logout:
                path:    logout
                target:  /
            remember_me:
                key:        juzz_cookie
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana

    access_control:
        - { path: ^/usuarios/(register|login|check-email|confirm), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios/*, roles: ROLE_USER }

    encoders:
        juzz\UsuariosBundle\Entity\Usuarios:
            algorithm: bcrypt
            cost:      11

    providers:
        users:
            entity: { class: juzz\UsuariosBundle\Entity\Usuarios, property: email }

