comments:
    path:     /comments/{target}
    defaults: { _controller: juzzCommentsBundle:Comments:getPosts }
    methods:  [GET]
    condition: "request.isXmlHttpRequest()"
    requirements:
        target:  \d*
post_comment:
    path:     /comments/new
    defaults: { _controller: juzzCommentsBundle:Comments:new }
    methods:  [POST]
    condition: "request.isXmlHttpRequest()"
comment_assess:
    path:     /comments/assess/{target}
    defaults: { _controller: juzzCommentsBundle:Comments:assess }
    methods:  [POST]
    condition: "request.isXmlHttpRequest()"
