services:
    notification_serialization_subscriber:
        class: juzz\NotificationsBundle\Listeners\NotificationSerializationSubscriber
        arguments: [@doctrine,@jms_serializer.serializer]
        tags:
           - { name: jms_serializer.event_subscriber }
