services:
    profile_image:
        class: juzz\FilesBundle\Form\ProfileImageType
        tags:
            - { name: form.type }
    profile_background_image:
        class: juzz\FilesBundle\Form\ProfileBackgroundType
        tags:
            - { name: form.type }

