episodios_categorias:
    path:     /categorias/{category}
    defaults: { _controller: juzzEpisodiosBundle:Episodios:categorias }
episodios_etiquetas:
    path:     /tags/{tag}
    defaults: { _controller: juzzEpisodiosBundle:Episodios:tags }
episodios_generos:
    path:     /generos/{genero}
    defaults: { _controller: juzzEpisodiosBundle:Episodios:generos }

